# config.yaml
# ───────────
video_source: "rtsp://user:pass@192.168.1.50:554/Streaming/Channels/1"

# Model paths
yolo_model: "models/yolov10n.pt"
cut_classifier: "models/pizza_cut_classifier_trained_model.pt"

# Output
save_dir: "output"

# Frame processing
frame_step: 2               # process every N-th frame
min_box_size: 20            # skip tiny detections
box_conf_filter: 0.40       # keep boxes ≥ this conf
yolo_conf: 0.30             # detector threshold
yolo_iou: 0.30              # NMS / tracker iou
tracker_cfg: "bytetrack.yaml"

# Hardware
device: "cuda"              # "cuda" or "cpu"